Update build to use PureScript

diff --git a/injps/script/build b/injps/script/build
--- a/injps/script/build
+++ b/injps/script/build
@@ -7,22 +7,35 @@ print_filesize() {
 
 echo "=> Building PureScript injectables"
 START=$(date +%s)
-pulp build --main Supple.Main --to ../dist/supple-inj.js
+
+pulp build --main Supple.Main --to ../dist/supple-main.js
 if [ $? -ne 0 ]; then
-    exit 1
+  echo "=> Failed to build main"
+  exit 1
 fi
-npx --quiet uglify-js --compress --mangle --output ../dist/supple-inj.min.js -- ../dist/supple-inj.js
+
+pulp build --main Supple.Checkout --to ../dist/supple-checkout.js
 if [ $? -ne 0 ]; then
-    exit 1
+  echo "=> Failed to build checkout"
+  exit 1
 fi
-gzip --keep --force ../dist/supple-inj.min.js
+
+npx --quiet uglify-js --compress --mangle --output ../dist/supple-main.min.js -- ../dist/supple-main.js
 if [ $? -ne 0 ]; then
-    exit 1
+  echo "=> Failed to minify main"
+  exit 1
 fi
+
+gzip --keep --force ../dist/supple-main.min.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to gzip main"
+  exit 1
+fi
+
 END=$(date +%s)
 BUILD_TIME=$(( $END - $START ))
 echo "=> Finished build in ${BUILD_TIME}s"
 echo "=> Build size:"
-print_filesize "supple-inj.js" "Raw Output"
-print_filesize "supple-inj.min.js" "Minified"
-print_filesize "supple-inj.min.js.gz" "Minified and Compressed"
+print_filesize "supple-main.js" "Raw Output"
+print_filesize "supple-main.min.js" "Minified"
+print_filesize "supple-main.min.js.gz" "Minified and Compressed"
