generate gzip size stats for checkout build

diff --git a/injps/script/build b/injps/script/build
--- a/injps/script/build
+++ b/injps/script/build
@@ -15,22 +15,9 @@ if [ $? -ne 0 ]; then
 fi
 echo "=> Finished building main"
 
-pulp build --main Supple.Checkout --to ../dist/supple-checkout.js
-if [ $? -ne 0 ]; then
-  echo "=> Failed to build checkout"
-  exit 1
-fi
-echo "=> Finished building checkout"
-
 npx --quiet uglify-js --compress --mangle --output ../dist/supple-main.min.js -- ../dist/supple-main.js
 if [ $? -ne 0 ]; then
   echo "=> Failed to minify main"
-  exit 1
-fi
-
-npx --quiet uglify-js --compress --mangle --output ../dist/supple-checkout.min.js -- ../dist/supple-checkout.js
-if [ $? -ne 0 ]; then
-  echo "=> Failed to minify checkout"
   exit 1
 fi
 
@@ -49,6 +36,27 @@ print_filesize "supple-main.min.js" "Minified"
 print_filesize "supple-main.min.js.gz" "Minified and Compressed"
 rm ../dist/supple-main.min.js.gz
 
+pulp build --main Supple.Checkout --to ../dist/supple-checkout.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to build checkout"
+  exit 1
+fi
+
+echo "=> Finished building checkout"
+npx --quiet uglify-js --compress --mangle --output ../dist/supple-checkout.min.js -- ../dist/supple-checkout.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to minify checkout"
+  exit 1
+fi
+
+gzip --keep --force ../dist/supple-main.min.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to gzip checkout"
+  exit 1
+fi
+
 echo "=> Build size checkout:"
 print_filesize "supple-checkout.js" "Raw Output"
 print_filesize "supple-checkout.min.js" "Minified"
+print_filesize "supple-checkout.min.js.gz"
+rm ../dist/supple-checkout.min.js.gz
