minifiy checkout script

diff --git a/injps/script/build b/injps/script/build
--- a/injps/script/build
+++ b/injps/script/build
@@ -28,6 +28,12 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+npx --quiet uglify-js --compress --mangle --output ../dist/supple-checkout.min.js -- ../dist/supple-checkout.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to minify checkout"
+  exit 1
+fi
+
 gzip --keep --force ../dist/supple-main.min.js
 if [ $? -ne 0 ]; then
   echo "=> Failed to gzip main"
@@ -37,7 +43,11 @@ fi
 END=$(date +%s)
 BUILD_TIME=$(( $END - $START ))
 echo "=> Finished build in ${BUILD_TIME}s"
-echo "=> Build size:"
+echo "=> Build size main:"
 print_filesize "supple-main.js" "Raw Output"
 print_filesize "supple-main.min.js" "Minified"
 print_filesize "supple-main.min.js.gz" "Minified and Compressed"
+
+echo "=> Build size:"
+print_filesize "supple-checkout.js" "Raw Output"
+print_filesize "supple-checkout.min.js" "Minified"
