Exit build script on build failure

diff --git a/injps/script/build b/injps/script/build
--- a/injps/script/build
+++ b/injps/script/build
@@ -17,13 +17,18 @@ elif [[ $ENV == "production" ]]; then
 fi
 
 spago bundle-app --main SweetSpot.Main --to ./output/sweetspot-main.js
-yarn --silent browserify --transform envify --outfile ../dist/sweetspot-main.js ./output/sweetspot-main.js
-
 if [ $? -ne 0 ]; then
   echo "=> Failed to build main"
   exit 1
 fi
 echo "=> Finished building main"
+
+yarn --silent browserify --transform envify --outfile ../dist/sweetspot-main.js ./output/sweetspot-main.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to bundle main"
+  exit 1
+fi
+echo "=> Finished bundling main"
 
 yarn --silent uglifyjs --compress --mangle --output ../dist/sweetspot-main.min.js ../dist/sweetspot-main.js
 if [ $? -ne 0 ]; then
@@ -47,14 +52,18 @@ print_filesize "sweetspot-main.min.js.gz" "Minified and Compressed"
 rm ../dist/sweetspot-main.min.js.gz
 
 spago bundle-app --main SweetSpot.Checkout --to ./output/sweetspot-checkout.js
-yarn --silent browserify --transform envify --outfile ../dist/sweetspot-checkout.js ./output/sweetspot-checkout.js
-
 if [ $? -ne 0 ]; then
   echo "=> Failed to build checkout"
   exit 1
 fi
 
-echo "=> Finished building checkout"
+yarn --silent browserify --transform envify --outfile ../dist/sweetspot-checkout.js ./output/sweetspot-checkout.js
+if [ $? -ne 0 ]; then
+  echo "=> Failed to bundle checkout"
+  exit 1
+fi
+echo "=> Finished bundling checkout"
+
 yarn --silent uglifyjs --compress --mangle --output ../dist/sweetspot-checkout.min.js ../dist/sweetspot-checkout.js
 if [ $? -ne 0 ]; then
   echo "=> Failed to minify checkout"
